### PR TITLE
fixed some small code and visual ish updates

### PR DESCRIPTION
**Pull request by BananaChad**
updated README.MD to match the new rarity changes and extras, updated rex but real.py to fix some simple issues and potentially a performance boost

### CODE REVIEW

**Review by terminite1 — CHANGES_REQUESTED** [review]
mnsising a modiule

**Review by BananaChad — COMMENTED** [review]
fixed the missing module and some mistakes i made in readme

**Comment by terminite1** [comment]
Shut ap

**Review by terminite1 — APPROVED** [review]
good

**Pull request merged**
